# 实验配置
experiment:
  name: "qwen_vl_token_pruning"
  output_dir: "./outputs"
  seed: 42
  device: "cuda"

# 数据配置
data:
  dataset_name: "MME"
  data_path: "./data/mme"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  batch_size: 8
  num_workers: 4
  max_length: 512
  image_size: 224

# 模型配置
model:
  base_model: "Qwen/Qwen-VL-3B"
  token_pruning:
    enabled: true
    method: "placeholder"
    prune_ratio: 0.3
  token_fusion:
    enabled: true
    method: "placeholder"
    fusion_threshold: 0.7

# 训练配置
training:
  learning_rate: 1e-5
  weight_decay: 0.01
  num_epochs: 10
  warmup_steps: 1000
  max_grad_norm: 1.0
  eval_steps: 500
  save_steps: 1000

# 评估配置
evaluation:
  metrics: ["accuracy", "f1", "perplexity"]
  save_predictions: true